name: Build and publish custom nginx image

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
    inputs:
      FORCE_BUILD:
        description: 'Force build even if image exists'
        type: boolean
        required: false
        default: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NGINX_FROM_IMAGE: nginx:mainline-alpine-slim

jobs:
  prepare:
    runs-on: ubuntu-24.04-arm
    outputs:
      BOM_SHA256: ${{ steps.bom.outputs.BOM_SHA256 }}
      BOM_SHA256_SHORT: ${{ steps.bom.outputs.BOM_SHA256_SHORT }}
      NGINX_VERSION: ${{ steps.bom.outputs.NGINX_VERSION }}
      NGINX_JWT_VERSION: ${{ steps.bom.outputs.NGINX_JWT_VERSION }}
      NGINX_KEYVAL_VERSION: ${{ steps.bom.outputs.NGINX_KEYVAL_VERSION }}
      NGX_ZSTD_VERSION: ${{ steps.bom.outputs.NGX_ZSTD_VERSION }}
      NGINX_OIDC_NJS_URL: ${{ steps.bom.outputs.NGINX_OIDC_NJS_URL }}
      SKIP_BUILD: ${{ steps.check_image.outputs.SKIP_BUILD }}
    steps:

      - name: Create current bill of materials
        id: bom
        run: |
          echo BASE_IMAGE_DIGEST=$(skopeo inspect docker://docker.io/${{ env.NGINX_FROM_IMAGE }} | jq -r '.Digest') | tee -a $GITHUB_OUTPUT >> bom
          echo $(skopeo inspect docker://docker.io/${{ env.NGINX_FROM_IMAGE }} | jq -r '.Env[] | select(contains("NGINX_VERSION"))') | tee -a $GITHUB_OUTPUT >> bom
          curl -fsSL https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/contrib/src/ngx_brotli/version >> bom
          curl -fsSL https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/contrib/src/ngx_http_geoip2_module/version >> bom
          curl -fsSL https://raw.githubusercontent.com/nginx/pkg-oss/refs/heads/master/contrib/src/njs/version >> bom
          echo NGINX_JWT_VERSION=$(curl -fsSL https://api.github.com/repos/kjdev/nginx-auth-jwt/tags | jq -r '.[0].name') | tee -a $GITHUB_OUTPUT >> bom
          echo NGINX_KEYVAL_VERSION=$(curl -fsSL https://api.github.com/repos/kjdev/nginx-keyval/tags | jq -r '.[0].name') | tee -a $GITHUB_OUTPUT >> bom
          echo NGX_ZSTD_VERSION=$(curl -fsSL https://api.github.com/repos/tokers/zstd-nginx-module/tags | jq -r '.[0].name') | tee -a $GITHUB_OUTPUT >> bom
          echo NGINX_OIDC_NJS_URL=$(curl -fsSL https://api.github.com/repos/jirutka/nginx-oidc-njs/releases | jq -r '.[0].assets.[] | select(.name | test("nginx-oidc-njs-.+\\.tar\\.gz$")) | .browser_download_url') | tee -a $GITHUB_OUTPUT >> bom
          echo OPENSSL_VERSION=$(docker run --rm alpine sh -c "apk update && apk list openssl | sed 's/^openssl-\(\S*\) .*$/\1/'" | tail -n 1) | tee -a $GITHUB_OUTPUT >> bom
          cat bom
          echo BOM_SHA256=$(sha256sum bom | head -c 64) | tee -a $GITHUB_OUTPUT
          echo BOM_SHA256_SHORT=$(sha256sum bom | head -c 8) | tee -a $GITHUB_OUTPUT

      - name: Check for existing image
        id: check_image
        run: |
          if skopeo inspect docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest | jq -r '.Labels["org.opencontainers.image.revision"]' | grep -q "${{ steps.bom.outputs.BOM_SHA256 }}"; then
            echo "Image already exists, skipping build unless forced."
            echo "SKIP_BUILD=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist, proceeding with build."
            echo "SKIP_BUILD=false" >> $GITHUB_OUTPUT
          fi

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: linux/amd64
          runner: ubuntu-24.04
        - platform: linux/arm64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    needs: prepare
    if: ${{ needs.prepare.outputs.SKIP_BUILD != 'true' || inputs.FORCE_BUILD == true }}
    permissions:
      contents: read
      packages: write
    steps:

      - name: Prepare
        id: prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" | tee -a $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.version=${{ needs.prepare.outputs.NGINX_VERSION }}
            org.opencontainers.image.revision=${{ needs.prepare.outputs.BOM_SHA256 }}
          annotations: |
            org.opencontainers.image.version=${{ needs.prepare.outputs.NGINX_VERSION }}
            org.opencontainers.image.revision=${{ needs.prepare.outputs.BOM_SHA256 }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare build context
        run: |
          curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Dockerfile-openssl-pre > Dockerfile
          curl -fsSL https://raw.githubusercontent.com/nginx/docker-nginx/refs/heads/master/modules/Dockerfile.alpine | sed '$s/$/ \\/; s/ARG ENABLED_MODULES/&\nARG NGX_KEYVAL_ZONE_REDIS/' >> Dockerfile
          echo '    && rm /usr/lib/nginx/modules/*-debug.so \' >> Dockerfile
          echo '    && mkdir -p /usr/local/share/nginx-oidc-njs \' >> Dockerfile
          echo '    && wget -qO- ${{ needs.prepare.outputs.NGINX_OIDC_NJS_URL }} | tar xz -C /usr/local/share/nginx-oidc-njs/ --strip-components=1' >> Dockerfile
          curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref }}/Dockerfile-openssl-post >> Dockerfile
          mkdir jwt keyval zstd
          echo jansson-dev > jwt/build-deps
          echo hiredis-dev > keyval/build-deps
          echo zstd-dev > zstd/build-deps
          echo https://github.com/kjdev/nginx-auth-jwt/archive/refs/tags/${{ needs.prepare.outputs.NGINX_JWT_VERSION }}.tar.gz > jwt/source
          echo https://github.com/kjdev/nginx-keyval/archive/refs/tags/${{ needs.prepare.outputs.NGINX_KEYVAL_VERSION }}.tar.gz > keyval/source
          # Pin commit SHA until https://github.com/tokers/zstd-nginx-module/pull/31#issuecomment-4169434111 is resolved:
          echo https://github.com/tokers/zstd-nginx-module/archive/f4ba115e0b0eaecde545e5f37db6aa18917d8f4b.tar.gz > zstd/source

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            NGINX_FROM_IMAGE=${{ env.NGINX_FROM_IMAGE }}
            ENABLED_MODULES=njs brotli geoip2 jwt keyval zstd
            NGX_KEYVAL_ZONE_REDIS=1
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ steps.prepare.outputs.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-24.04-arm
    needs:
      - prepare
      - build
    steps:

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          annotations: |
            org.opencontainers.image.version=${{ needs.prepare.outputs.NGINX_VERSION }}
            org.opencontainers.image.revision=${{ needs.prepare.outputs.BOM_SHA256 }}
          tags: |
            latest
            ${{ needs.prepare.outputs.NGINX_VERSION }}
            ${{ needs.prepare.outputs.NGINX_VERSION }}-${{ needs.prepare.outputs.BOM_SHA256_SHORT }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          CMD='docker buildx imagetools create'
          CMD+=' '
          CMD+=$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          CMD+=' '
          CMD+=$(jq -cr '.annotations | map("--annotation \"" + . + "\"") | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          CMD+=' '
          CMD+=$(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)
          eval $CMD

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
